server:
  port: ${PORT:0}
spring:
  application:
    name: api-facade
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

#swagger
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
    tagsSorter: alpha
    display-query-params-without-oauth2: true
    use-root-path: true
  cache:
    disabled: true
  #jackson
  jackson:
    time-zone: America/Santiago
    locale: es_CL
#logging
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
#feign
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
#eureka settings
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    should-unregister-on-shutdown: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 45
    statusPageUrlPath: /infoApiFacade
    healthCheckUrlPath: /healthApiFacade
    metadataMap:
      appOwner: TeamWeichafe
      description: api-facade
management:
  endpoint:
    web:
      exposure:
        include: hystrix.stream, info, health
    health:
      show-details: always


